[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
markers =
    integration: tests that require external services
    kafka: tests that require a running Kafka broker and, where relevant, running Processors
    postgres: tests that require a running PostgreSQL database
